# Generated by Django 2.2.13 on 2020-08-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycalendar',
            name='ics',
            field=models.FileField(blank=True, null=True, upload_to='ics/'),
        ),
    ]
