# Generated by Django 4.2.1 on 2023-05-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0002_mycalendar_ics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycalendar',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
