# Generated by Django 5.2.13 on 2026-04-26 13:23

import mycalendar.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0003_alter_mycalendar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycalendar',
            name='document',
            field=models.FileField(upload_to='documents/', validators=[mycalendar.validators.validate_csv_upload]),
        ),
    ]
