# Generated by Django 5.2.13 on 2026-06-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0004_alter_mycalendar_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycalendar',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
