"""
Django settings for django_myical project.

Generated by 'django-admin startproject' using Django 2.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

from pathlib import Path

import environ
from django.utils.translation import gettext_lazy as _

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, []),
    CSRF_TRUSTED_ORIGINS=(list, []),
    MAX_UPLOAD_BYTES=(int, 1024 * 1024),
    EVENT_DURATION_MINUTES=(int, 90),
    SITE_TIMEZONE=(str, "Europe/Brussels"),
    HSTS_SECONDS=(int, 60 * 60 * 24 * 30),
    HSTS_INCLUDE_SUBDOMAINS=(bool, False),
    HSTS_PRELOAD=(bool, False),
)
environ.Env.read_env(BASE_DIR / ".env")

SECRET_KEY = env("SECRET_KEY")
DEBUG = env("DEBUG")
ALLOWED_HOSTS = env("ALLOWED_HOSTS")
SITE_DOMAIN = env("SITE_DOMAIN", default="localhost")
# Canonical env label is STATE (fleet OPERATIONS.md §3.14); fall back to the
# legacy DJANGO_ENV (ical only ever used it as a label, never a settings-module
# dispatch) until the SSM rename is migrated.
STATE = env("STATE", default="") or env("DJANGO_ENV", default="DEV")
CSRF_TRUSTED_ORIGINS = env("CSRF_TRUSTED_ORIGINS")
MAX_UPLOAD_BYTES = env("MAX_UPLOAD_BYTES")
EVENT_DURATION_MINUTES = env("EVENT_DURATION_MINUTES")
SITE_TIMEZONE = env("SITE_TIMEZONE")

# Database. DATABASE_URL (when set) WINS — the clean_import tooling/tests point
# the app at a specific sqlite file via DATABASE_URL. Otherwise the fleet DB_*
# 6-var convention (OPERATIONS.md §3.5): unset → sqlite at BASE_DIR/db.sqlite3;
# prod uses local PostgreSQL (DB_ENGINE=postgresql, DB_HOST=127.0.0.1, ...).
_db_url = env("DATABASE_URL", default="")
if _db_url:
    DATABASES = {"default": env.db("DATABASE_URL")}
else:
    _DB_ENGINE_ALIASES = {
        "sqlite3": "django.db.backends.sqlite3",
        "postgresql": "django.db.backends.postgresql",
        "postgres": "django.db.backends.postgresql",
    }
    _db_engine = env("DB_ENGINE", default="sqlite3")
    DATABASES = {
        "default": {
            "ENGINE": _DB_ENGINE_ALIASES.get(_db_engine, _db_engine),
            "NAME": env("DB_NAME", default=str(BASE_DIR / "db.sqlite3")),
            "USER": env("DB_USER", default=""),
            "PASSWORD": env("DB_PASSWORD", default=""),
            "HOST": env("DB_HOST", default=""),
            "PORT": env("DB_PORT", default=""),
        }
    }

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'mycalendar'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_myical.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django_myical.context_processors.site_state',
            ],
            'libraries': {
                'common_tags': 'common_tags',
                'admin.urls': 'django.contrib.admin.templatetags.admin_urls',
            },
        },
    },
]

WSGI_APPLICATION = 'django_myical.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
LANGUAGES = (
    ('en', _('English')),
    ('fr', _('Français')),
    ('nl', _('Nederlands')),
)

TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True
LOCALE_PATHS = [BASE_DIR / 'locale']

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Security headers — only enforce HTTPS-related ones outside DEBUG.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = env("HSTS_SECONDS")
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool("HSTS_INCLUDE_SUBDOMAINS", default=False)
    SECURE_HSTS_PRELOAD = env.bool("HSTS_PRELOAD", default=False)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "same-origin"
    X_FRAME_OPTIONS = "DENY"

# WhiteNoise for static files.
STATIC_ROOT = BASE_DIR / "staticfiles"
_staticfiles_backend = (
    "whitenoise.storage.CompressedManifestStaticFilesStorage"
    if not DEBUG
    else "django.contrib.staticfiles.storage.StaticFilesStorage"
)
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": _staticfiles_backend},
}

# Logging — surface ICS build failures in prod logs.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "root": {"handlers": ["console"], "level": "INFO"},
    "loggers": {
        "mycalendar": {"handlers": ["console"], "level": "INFO", "propagate": True},
    },
}

# File upload limits.
DATA_UPLOAD_MAX_MEMORY_SIZE = MAX_UPLOAD_BYTES
FILE_UPLOAD_MAX_MEMORY_SIZE = MAX_UPLOAD_BYTES

# Map Django's 'error' message tag to Bootstrap's 'danger' alert class.
from django.contrib.messages import constants as messages_const  # noqa: E402

MESSAGE_TAGS = {messages_const.ERROR: "danger"}

# Sentry — optional. Set SENTRY_DSN to enable.
SENTRY_DSN = env("SENTRY_DSN", default="")
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from django.core.exceptions import DisallowedHost

    def _drop_benign_noise(event, hint):
        # Internet scanners hit the raw EC2 IP; ical is nginx's implicit default vhost,
        # so Django rejects them as DisallowedHost (400). That rejection is the correct,
        # intended behaviour — not an error worth paging on. Drop it instead of letting
        # bot traffic flood Sentry (~500/day). Do NOT "fix" this by adding the IP to
        # ALLOWED_HOSTS — that would make Django serve Host-spoofed requests.
        exc = hint.get("exc_info")
        if exc and isinstance(exc[1], DisallowedHost):
            return None
        return event

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        environment=env("SENTRY_ENVIRONMENT", default="") or STATE,
        traces_sample_rate=0.1,
        send_default_pii=False,
        before_send=_drop_benign_noise,
    )
