server {
    listen 80;
    server_name ical.foxugly.com;

    client_max_body_size 2M;

    location /media/ {
        alias /var/www/django_websites/django-ical/media/;
        location ~ \.(php|phtml|py|pl|cgi|sh|exe)$ {
            deny all;
        }
    }

    location / {
        proxy_pass http://unix:/run/django-ical/django-ical.sock;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
